server:
  #  port: 8002
  servlet:
    context-path: /zero

spring:
  application:
    name: zero-server
  profiles:
    active: 23
  resources:
    add-mappings: false
    static-locations: classpath:/static/,classpath:/templates/index/
    #,classpath:/META-INF/resources/webjars/,classpath:/META-INF/resources
  #   static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  #,file:${web.upload-path},file:${web.vue-path}
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #https://blog.csdn.net/zoeou/article/details/78629032
  security:
    user:
      name: root
      password: admin

#配置日志,日志用xml去配置
log:
  dir: ./log

  #mybatis:
  #为实体对象所在的包，跟数据库表一一对应
  #  type-aliases-package: com.arc.model.common
  #mapper文件的位置
#  mapper-locations: classpath:mapper/*/*.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.log4j2.Log4j2LoggerImpl
  type-enums-package: com.arc.core.enums.common.*
# 自定义参数；说明 1、web.system.initial:是否在系统启动的时候初始化一些操作
web:
  upload:
    file: /
  system:
    initial: true
#  key: ZZ

##actuator健康管理
#management:
#  server:
#    port: 8001
##    servlet:
##      context-path: /ac
#  endpoints:
#    web:
#      exposure:
##        include: health,info,env,metrics,beans,configprops,conditions,mappings,loggers,heapdump
#        include: health,info,env,beans,mappings,loggers
#  endpoint:
#    shutdown:
#      enabled: true

